include:
  - project: pipelines/pipelines
    ref: main
    file:
      - "/jobs/build.yaml"
      - "/jobs/rules.yaml"

.global-variables:
  interruptible: true
  variables:
      DOCKERFILE_PATH: dockerfile
      DOCKER_CONFIG: /kaniko/.docker
      CONTEXT: $CI_PROJECT_DIR
      IMAGE_TAG: $CI_COMMIT_SHA
      IMAGE_NAME: $CI_REGISTRY_IMAGE:$IMAGE_TAG
      REGISTRY_USER: $CI_REGISTRY_USER
      REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
      REGISTRY_URL: $CI_REGISTRY

stages:
  - build
  - tests
  - export

build:
  stage: build
  extends:
    - .build
    - .global-variables
    - .rules-merge-or-master

tests:
  stage: tests
  extends:
    - .rules-merge-or-master
    - .global-variables
  image: $IMAGE_NAME
  variables:
    PLAYWRIGHT_JUNIT_OUTPUT_FILE: "test-results/results.xml"
  script:
    - npx playwright test --reporter=junit || exit 0
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - test-results/
    reports:
      junit: test-results/results.xml

export:
  stage: export
  image: curlimages/curl:8.10.1
  extends:
    - .global-variables
    - .rules-master
  needs:
    - job: tests
      artifacts: true
  rules:
    - when: on_success
  script:
    - |
      curl -sS --fail -X POST "$EXPORT_URL/api/v1/submissions" \
        -H "Authorization: Bearer $EXPORT_API_KEY" \
        -F "repo_name=$CI_PROJECT_NAME" \
        -F "$TRACK" \
        -F "ci_job_id=$CI_JOB_ID" \
        -F "junit_xml=@test-results/results.xml" \
        >/dev/null 2>&1 || true
